# apps/*/Dockerfile.dev
FROM node:20-alpine

# Установка зависимостей
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm ci

# Копируем исходный код (в dev он будет переопределён volume'ом)
COPY . .

# Порт (может отличаться: 3001, 3002, 3003)
EXPOSE 3000

# Запуск с live-reload (NestJS watch mode)
CMD ["npm", "run", "start:dev:nodemon"]